Week 1 Notes
JacquesCarette/COMPSCI3MI3-F2023 pull request #1
Opened 2023-09-12 00:20 UTC by demanr

Here are my notes for week 1 in Markdown, with added links.

2023-09-12 17:09 UTC, JacquesCarette commented
This is fantastic. I have a number of corrections to make, so I'll do a full review soon, and then merge in this PR.

I would happily accept more PRs like this (for bonus grades, naturally - it is extra work).

2023-09-13 19:32 UTC, JacquesCarette requested changes
A few things to fix - thanks again.

2023-09-13 19:32 UTC, JacquesCarette commented on Lecture/Week1Lecture1&2Notes.md
> +	- dynamic scope for if statements (fortran had static)
dynamic scope for variables, not if statements. See https://prl.khoury.northeastern.edu/blog/2019/09/05/lexical-and-dynamic-scope/ and https://en.wikipedia.org/wiki/Scope_(computer_science)

2023-09-13 19:32 UTC, JacquesCarette commented on Lecture/Week1Lecture1&2Notes.md
> +- [Original Website](https://algol60.org/)
should also link to the Algol page

2023-09-13 19:32 UTC, JacquesCarette commented on Lecture/Week1Lecture1&2Notes.md
> +- Used a lot of OOP
Is the first truly OO language, and most ideas of OO that were not already in Simula 67 come from here

2023-09-13 19:32 UTC, JacquesCarette commented on Lecture/Week1Lecture1&2Notes.md
> +- old but still used today
mostly for embedded software

2023-09-13 19:32 UTC, JacquesCarette commented on Lecture/Week1Lecture1&2Notes.md
> +# OS2
OS/2 is an operating system, not a programming language. That part isn't testable material, that was just a story from my past.

2023-09-13 19:32 UTC, JacquesCarette commented on Lecture/Week1Lecture1&2Notes.md
> +# Snowbol
Snobol

2023-09-14 00:03 UTC, demanr commented on Lecture/Week1Lecture1&2Notes.md
> +	- dynamic scope for if statements (fortran had static)
Good to know, thanks

2023-09-14 00:05 UTC, demanr commented on Lecture/Week1Lecture1&2Notes.md
> +- [Original Website](https://algol60.org/)
I couldn't find an Algol page, could you please elaborate a bit on what you're looking for?

2023-09-14 00:07 UTC, JacquesCarette commented on Lecture/Week1Lecture1&2Notes.md
> +- [Original Website](https://algol60.org/)
https://en.wikipedia.org/wiki/ALGOL

2023-09-14 02:43 UTC, demanr commented on Lecture/Week1Lecture1&2Notes.md
> +- [Original Website](https://algol60.org/)
Thanks!

2023-09-14 02:45 UTC, demanr commented
Should be good now

2023-09-14 17:25 UTC, JacquesCarette approved these changes

2023-09-14 17:25 UTC, merged